name: Flutter Web Actions
run-name: ${{ github.actor }} is build flutter web app on Google Actions to Google Pages.
on: [push]
jobs:
    Explore-GitHub-Actions:
        runs-on: ubuntu-latest
        steps:
            -   name: Clone repository
                uses: actions/checkout@v4
            -   name: Set up Flutter
                uses: subosito/flutter-action@v2
                with:
                    channel: stable
            -   run: flutter pub get
            -   run: flutter test
            -   run: flutter build web