name: Flutter Web Actions
run-name: ${{ github.actor }} is build flutter web app on Google Actions to Google Pages.
on: [push]
jobs:
    Explore-GitHub-Actions:
        runs-on: ubuntu-latest
        steps:
            -   name: Clone repository
                uses: actions/checkout@v4
            -   name: Set up Flutter
                uses: subosito/flutter-action@v2
                with:
                    channel: stable
            -   run: flutter pub get
            -   run: flutter test
            -   run: flutter build web
            - run: |
                cd build/web
                git init
                git config --global user.email disaeye@gmail.com
                git config --global user.name Disaeye
                git status
                git remote add origin https://${{secrets.COMMITSECRET}}@github.com/disaeye/MyFirstFlutter.git
                git checkout -b showcase
                git add --all
                git commit -m "update"
                git push origin showcase -f